### PR TITLE
Maybe not using snapshot fabric-api in release minecraft will make the mod more stable

### PR DESCRIPTION
**Pull request by KosmX**
*definitely* related to #34

### CODE REVIEW

**Comment by KirboSoftware** [comment]
@FluffyBumblebees care to explain why we're using snapshot stuff in the main version? Also, will review the changes asap @KosmX Thank you for the time.

**Review by KirboSoftware — APPROVED** [review]
Tested these changes and made it work. Thanks for this KosX!

**Comment by KosmX** [comment]
I'm not sure, why did you `include` this library without using in development environment, maybe removing it from the mod would be better.
(And everyone install fabric-api, including it is not required.)

**Comment by KirboSoftware** [comment]
Idk either, I'm as surprised about it as you kosmx. 

Tho I do agree to have those things in a dev env or something and not having that in the `main` branch

**Comment by StockiesLad** [comment]
The embedded module is for the translations to work

**Pull request merged**
