### PR TITLE
Fix gradlew wrapper permissions

### PR DESCRIPTION
**Pull request by ghost**
Changes the permission of the "gradlew" script to allow for this mod to be built on Linux, without having to `chmod +x gradlew` .

### CODE REVIEW

**Comment by StockiesLad** [comment]
@JoostMSoftware can u check this out when u have time?

**Comment by KirboSoftware** [comment]
@StockiesLad is this really something we need? Like I use linux myself and I don't really see the need for this imo? But hey, if you think this is required. I can merge it

**Comment by StockiesLad** [comment]
> @StockiesLad is this really something we need? Like I use linux myself and I don't really see the need for this imo? But hey, if you think this is required. I can merge it

Can't hurt to have extra compat.

**Comment by KirboSoftware** [comment]
Fair enough, will test it and see if it requires some fixing (to merge)

**Comment by ghost** [comment]
> @StockiesLad is this really something we need? Like I use linux myself and I don't really see the need for this imo? But hey, if you think this is required. I can merge it

Yes, this pull request allows execution of the gradlew wrapper without manually having to change the execution perms, which is useful if you want to build the project from source using only CLI.

**Comment by StockiesLad** [comment]
> > @StockiesLad is this really something we need? Like I use linux myself and I don't really see the need for this imo? But hey, if you think this is required. I can merge it
> 
> Yes, this pull request allows execution of the gradlew wrapper without manually having to change the execution perms, which is useful if you want to build the project from source using only CLI.

Are there any potential risks of modifying the perms. I don't want to merge just to find it breaks on my machine.

**Comment by Kichura** [comment]
One fix i could suggest is modifying github actions to also not include the chmod +x gradlew command as it is no longer needed.

**Comment by StockiesLad** [comment]
Can u put this in ur PR

**Comment by KirboSoftware** [comment]
> > @StockiesLad is this really something we need? Like I use linux myself and I don't really see the need for this imo? But hey, if you think this is required. I can merge it
> 
> Yes, this pull request allows execution of the gradlew wrapper without manually having to change the execution perms, which is useful if you want to build the project from source using only CLI.

Fair enough. I didn't think of that

**Comment by ghost** [comment]
> > > @StockiesLad is this really something we need? Like I use linux myself and I don't really see the need for this imo? But hey, if you think this is required. I can merge it
> > 
> > 
> > Yes, this pull request allows execution of the gradlew wrapper without manually having to change the execution perms, which is useful if you want to build the project from source using only CLI.
> 
> Are there any potential risks of modifying the perms. I don't want to merge just to find it breaks on my machine.

No. This pull request will not cause ANY issues whatsoever.

**Comment by ghost** [comment]
> One fix i could suggest is modifying github actions to also not include the chmod +x gradlew command as it is no longer needed.

I have removed the chmod +x step from the GitHub action workflow in this PR. Thank you.

**Review by Kichura — APPROVED** [review]
LGTM.

**Comment by StockiesLad** [comment]
alright can u make one for 1.18.2 as well? I am planning on abstracting my code (bc 1.18.2 branch has some fixes) to run on all versions.

**Comment by ghost** [comment]
> alright can u make one for 1.18.2 as well? I am planning on abstracting my code (bc 1.18.2 branch has some fixes) to run on all versions.

#56

**Pull request merged**
